### ISSUE TITLE
Why isn't `tok->next` in `is_function()`

### ISSUE THREAD

**Issue by sunshaoce** [rui314/chibicc#102]
https://github.com/rui314/chibicc/commit/a4d3223a7215712b86076fad8aaf179d8f768b14#r81000554

**Comment by sunshaoce** [comment]
```
static bool is_function(Token *tok) {
  if (equal(tok, ";"))
    return false;

  Type dummy = {};
  Type *ty = declarator(&tok, tok, &dummy);
  return ty->kind == TY_FUNC;
}
```
I think `if (equal(tok, ";"))` could be `if (equal(tok->next, ";"))`

**Comment by siriusdemon** [comment]
Hey @sunshaoce  I am also studying these code too. 
I think the `if` check  whether this is a type declaration. like
```c
int;  // this is type declaration
int main() { ... }
```

**Comment by sunshaoce** [comment]
I see, thank you!
