### ISSUE TITLE
#include errors are reported on the wrong line

### ISSUE THREAD

**Issue by joefarebrother** [rui314/chibicc#12]
The following file:

```c
#include "fake.h"

int main() {}
```
where `fake.h` does not exist
produces the output

```
fail_include.c:3: int main() {}
                  ^ fake.h: cannot open file: No such file or directory
```

whereas the error should instead be reported on the `#include` line.

**Comment by rui314** [comment]
It looks like `#include` error is reported against the next token of the `#include` line. That's not a severe error but certainly confusing. Thank you for reporting.

**Comment by rui314** [comment]
This problem has been fixed. Now chibicc prints out an error message in the following way.

```
/tmp/foo.c:1: #include "foo"
                       ^ foo: cannot open file: No such file or directory
```
