### ISSUE TITLE
Provide a way to get a notification when the book launches

### ISSUE THREAD

**Issue by heyvito** [rui314/chibicc#15]
Hi there! I recently came across this repository, and would like to say I'm really eager to get the book once it's ready.
Could you consider creating a mailing list, or something like that so we can get a straightforward way to know when the book is available for purchase? I'd appreciate that.

Thank you!

**Comment by rui314** [comment]
OK, I set up a Google Form to collect email addresses for notifications. You can sign-up here. https://forms.gle/sgrMWHGeGjeeEJcX7. I added a link to this form to README.
