### ISSUE TITLE
semantic errors  uncatched

### ISSUE THREAD

**Issue by lingxiaotang** [rui314/chibicc#28]
It seems that many semantic errors are not catched.For example,the type of a bit field has to be int or unsigned,but the compiler seems not to check this. I may wonder if the front end is not completed.
```C
struct a {
    int;
    double d:10;
}A;
```
                                                                                                                                                                                             thank you

**Comment by rui314** [comment]
I'd say that the frontend is complete, but as a matter of policy, it doesn't rigorously check for errors. My primary focus was on compiling correct code correctly and everything else is secondary. I want to add more error checks in future, though.

**Comment by lingxiaotang** [comment]
Thank you for your explaination. I'm looking forward to your future work such as intermediate code generation.
