### ISSUE TITLE
Thanks and roadmap

### ISSUE THREAD

**Issue by bleuge** [rui314/chibicc#29]
I like very much your design principles, I tend to work the same way, read some source files and code is clean and easy to follow.
Is the compiler complete?, I mean, can I start reading right now or do you plan to introduce big changes in the future?. 
Or maybe do you have a roadmap worth including in the readme?
I've been toying with a small compiler that produces code for a small 8bit VM, not C, but still have lots of things to finish. 
Thanks for inspiration!

**Comment by rui314** [comment]
I think I can say that the compiler is almost complete. You can start reading it today as it already achieves its goal which is to provide an easy-to-read compiler implementation. I'm planning to add a new backend which optimizes output code, but that will be an addition to the current code base and shouldn't affect most of the existing code.

**Comment by bleuge** [comment]
Great, it would be nice to learn better about code generation and optimization. I don't need it for this hobby project as the idea is simple scripts for a 8bit VM. Thanks!
