### ISSUE TITLE
linker fails

### ISSUE THREAD

**Issue by unihernandez22** [rui314/chibicc#4]
```
ld: cannot find /usr/lib/x86_64-linux-gnu/crt1.o: No such file or directory
ld: cannot find /usr/lib/x86_64-linux-gnu/crti.o: No such file or directory
ld: cannot find /usr/lib/gcc/x86_64-linux-gnu/9/crtbegin.o: No such file or directory
```

**Comment by unihernandez22** [comment]
I think the compiler isn't prepared for that, but that (self-compiling) should be the next step. :smile:

**Comment by unihernandez22** [comment]
Ok I get that error when compiling anything

**Comment by rui314** [comment]
I'm testing this compiler only on my Ubuntu 20 machine. On your system, crt1.o and crtbegin.o might be at a different place. Can you run `find /usr/lib -name crt1.o`?

**Comment by tankf33der** [comment]
Void Linux x64
```
# find /usr/lib -name crt1.o
/usr/lib/crt1.o
```

**Comment by rui314** [comment]
If you modify the hard-coded paths in the source code, the compiler should work. Perhaps I have to implement a logic to search for the files from a list of directories that may have the files. That's a to-do.

**Comment by unihernandez22** [comment]
Maybe the paths depends on gcc version

**Comment by unihernandez22** [comment]
If someone uses gcc 10.2.0 then [here](https://github.com/unihernandez22/chibicc/tree/gcc-10.2.0) is the code with correct paths.

**Comment by edubart** [comment]
I've applied the patch from @unihernandez22  for GCC 10.2.0 but now I get:
```
/chibicc test/enum.c 
ld: /tmp/chibicc-kyrtGR: in function `main':
(.text+0xa2): undefined reference to `assert'
ld: (.text+0xd5): undefined reference to `assert'
ld: (.text+0x108): undefined reference to `assert'
ld: (.text+0x13b): undefined reference to `assert'
ld: (.text+0x16e): undefined reference to `assert'
ld: /tmp/chibicc-kyrtGR:(.text+0x1a1): more undefined references to `assert' follow
```

Workarounds?

**Comment by MattWindsor91** [comment]
> Maybe the paths depend on gcc version

This seems like it's the case, since on my Ubuntu 18.04 machine (GCC 7.4.0) the correct path is `/usr/lib/gcc/x86_64-linux-gnu/7/` (and there is also, for some reason, a `/usr/lib/gcc/x86_64-linux-gnu/8/`).

**Comment by rui314** [comment]
I made a change to search for directories for crt* files. Verified that the change works on Ubuntu 18, Ubuntu 20 and Gentoo.
