### ISSUE TITLE
Unnatural associativity of arithmetic operators in parser

### ISSUE THREAD

**Issue by StrongerXi** [rui314/chibicc#44]
The following program
```c
int printf(char *fmt, ...);

int println_id(int x) {
  printf("%d\n", x);
  return x;
}

int main() {
  return println_id(1) + println_id(2) + println_id(3);
}
```
compiles to something that contains
```assembly
  mov $3, %rax
  push %rax
  .loc 1 9
  lea println_id(%rip), %rax
  pop %rdi
  mov %rax, %r10
  mov $0, %rax
  call *%r10
  add $0, %rsp
  push %rax
  .loc 1 9
  .loc 1 9
  .loc 1 9
  .loc 1 9
  sub $8, %rsp
  .loc 1 9
  .loc 1 9
  mov $2, %rax
  push %rax
  .loc 1 9
  lea println_id(%rip), %rax
  pop %rdi
  mov %rax, %r10
  mov $0, %rax
  call *%r10
  add $8, %rsp
  push %rax
  .loc 1 9
  .loc 1 9
  .loc 1 9
  .loc 1 9
  mov $1, %rax
  push %rax
  .loc 1 9
  lea println_id(%rip), %rax
  pop %rdi
  mov %rax, %r10
  mov $0, %rax
  call *%r10
```

I can't run the code since I have MacOS, but from the assembly above the call sequence seems to be `println_id(3)`, `println_id(2)`, and `println_id(1)`.

I was wondering how your recursive descent parser handles operator associativity, and the following part of the parser led me to discover this "issue":
```c
...
// add = mul ("+" mul | "-" mul)*
static Node *add(Token **rest, Token *tok) {
...
```

"+" and "-" seems to be right-associative, instead of the more natural "left-associative".

**Comment by rui314** [comment]
I think this is not about operator precedence but about the order of evaluation. Your code depends on an implementation-defined behavior.

`+` and `-` are left-associative, so A+B-C is interpreted as (A+B)-C. But it doesn't mean A+B is evaluated before C. `-` can evaluate the right-hand side first and then the left-hand side. The language spec doesn't guarantee any evaluation order for most binary operators (except `&&` and `||` for the obvious reason).

So, don't do this:

```
return println_id(1) + println_id(2) + println_id(3);
```

Instead, do this:

```
int x = println_id(1);
int y = println_id(2);
int z = println_id(3);
return x + y + z;
```
