### ISSUE TITLE
is_variadic is being set on 0-arity functions

### ISSUE THREAD

**Issue by bsdunx** [rui314/chibicc#46]
https://github.com/rui314/chibicc/blob/90d1f7f199cc55b13c7fdb5839d1409806633fdb/parse.c#L625
I'm going to assume you meant to set the flag to false on nil arg va func to supress register preservation? At any rate I want to show my appreciation for this project, it really helped clarify a few aspects of the process, regards! :heart:

**Comment by bsdunx** [comment]
Sorry I thought about this some more and realized it is done to handle functions with unspecified arguments, a confusion of `int foo();` vs `int foo(void);` on my part. Reopen if my determination is incorrect. Perhaps a comment is in order just to clarify.

**Comment by JonathanWilbur** [comment]
I noticed this too, and I started to write up an issue before noticing that somebody else already did. I am pasting part of what I wrote up just for documentation purposes:

https://github.com/rui314/chibicc/blob/90d1f7f199cc55b13c7fdb5839d1409806633fdb/parse.c#L625-L626

This causes `va_area` to be defined for the `Obj` representing the function here:

https://github.com/rui314/chibicc/blob/90d1f7f199cc55b13c7fdb5839d1409806633fdb/parse.c#L3241-L3242

...which causes the generated assembly to add a lot of extra instructions to push all of the registers to the stack.

https://github.com/rui314/chibicc/blob/90d1f7f199cc55b13c7fdb5839d1409806633fdb/codegen.c#L1497-L1531

**Comment by fuhsnn** [comment]
Having `is_variadic` has the benefit of calling external K&R old style functions, on x86-64 they happen to have the [same ABI](https://godbolt.org/z/j4nrKx4Mx).

I think it's safe to just treat them like `fn(void)` if you don't need the hidden compatibility. chibicc would [error](https://godbolt.org/z/znEMbG6a5) on declaring K&R functions anyway.
