### ISSUE TITLE
`-exec rm {}` vs `-delete` in Makefile

### ISSUE THREAD

**Issue by stefanos82** [rui314/chibicc#74]
In the following line,

https://github.com/rui314/chibicc/blob/90d1f7f199cc55b13c7fdb5839d1409806633fdb/Makefile#L48

you use `-exec rm {}` over `-delete`.

Is there a particular reason or it's just a personal preference?

```sh
Old way: find * -type f '(' -name '*~' -o -name '*.o' ')' -exec rm {} ';'
New way: find * -type f '(' -name '*~' -o -name '*.o' ')' -delete
```

**Comment by michaelforney** [comment]
One reason to prefer `-exec rm {} ';'` or `-exec rm {} +` is that `-delete` is not a standard option to find(1). Some implementations don't support it.

See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html

**Comment by rui314** [comment]
As @michaelforney pointed out, it's for portability. I learned the find command a long time ago, so I didn't even know the find command of the GNU version has gained the `-delete` option.

**Comment by stefanos82** [comment]
Ah so it's not a portable feature; I see...well my curiosity got its answer :smile: 

Thank you @michaelforney and @rui314 :+1: 

P.S.: @rui314 any progress with the book?

**Comment by rui314** [comment]
@stefanos82 No, unfortunately. These days I've been busy working on another project, https://github.com/rui314/mold.

**Comment by stefanos82** [comment]
Yeah, I know `mold` and honestly I found it really cool, even though I haven't used it yet; just studying your code style for now.
