### ISSUE TITLE
Missing headers?

### ISSUE THREAD

**Issue by Andersama** [rui314/chibicc#77]
Pretty sure this might be an issue because I'm building on windows. in chibicc.h here's what appears missing: glob.h, libgen.h, strings.h sys/wait.h and unistd.h. May also be an issue that I attempted to make a cmake project and maybe the make file would've told the compiler where those were, the headers though I think are linux based, not sure, could be wrong.

In any case looking forward to the book.

**Comment by rui314** [comment]
chibicc can be built only on Linux and produces Linux executables. Windows is not supported. If you want to built and try out chibicc on Windows, please use WSL (Windows Subsystem for Linux).

**Comment by Andersama** [comment]
Ah ok, good to get direct feedback I sort've figured that's what was going on. Thanks.
