### ISSUE TITLE
unicode identifiers

### ISSUE THREAD

**Issue by rurban** [rui314/chibicc#79]
C23 has now more restrictions
https://github.com/rui314/chibicc/blob/90d1f7f199cc55b13c7fdb5839d1409806633fdb/unicode.c#L98

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2731.pdf

N2731 Annex D (normative)
  Universal character names for identifiers
  This clause lists the hexadecimal code values that are valid in universal character
  names in identifiers.

  D.1 Ranges of characters allowed

  00A8, 00AA, 00AD, 00AF, 00B2–00B5, 00B7–00BA, 00BC–00BE, 00C0–00D6, 00D8–00F6, 00F8–00FF
  0100–167F, 1681–180D, 180F–1FFF
  200B–200D, 202A–202E, 203F–2040, 2054, 2060–206F
  2070–218F, 2460–24FF, 2776–2793, 2C00–2DFF, 2E80–2FFF
  3004–3007, 3021–302F, 3031–303F
  3040–D7FF
  F900–FD3D, FD40–FDCF, FDF0–FE44, FE47–FFFD
  10000–1FFFD, 20000–2FFFD, 30000–3FFFD, 40000–4FFFD, 50000–5FFFD, 60000–6FFFD, 70000–
  7FFFD, 80000–8FFFD, 90000–9FFFD, A0000–AFFFD, B0000–BFFFD, C0000–CFFFD, D0000–DFFFD,
  E0000–EFFFD

  D.2 Ranges of characters disallowed initially
  0300–036F, 1DC0–1DFF, 20D0–20FF, FE20–FE2F

FDF0–FE44, FE47–FFFD minus FE20–FE2F
vs   0xFDF0 - 0xFE1F, 0xFE30-0xFE44, 0xFE47-0xFFFD,

Not talking here about the insecurities in allowing insecure mixed scripts, such as Greek together with Cyrillic.

**Comment by rurban** [comment]
Oops, I was wrong

**Comment by rui314** [comment]
Well, C23 isn't standardized yet. We don't need to conform to the draft of it.
