### ISSUE TITLE
jumping into statement expression can cause weird behavior

### ISSUE THREAD

**Issue by ghost** [rui314/chibicc#82]
Consider:

~~~ C
#include <stdio.h>

int main(void)
{
	goto bar;
	printf("%d %d %d\n", 12, ({bar: puts("hello"); 34;}), 56);
	return 0;
}
~~~

This program will show:

~~~
hello
12 34 <arbitrary integer>
~~~

GCC simply disallows that:

~~~
test.c: In function ‘main’:
test.c:5:9: error: jump into statement expression
    5 |         goto bar;
      |         ^~~~
test.c:6:36: note: label ‘bar’ defined here
    6 |         printf("%d %d %d\n", 12, ({bar: puts("hello"); 34;}), 56);
      |                                    ^~~
~~~

**Comment by rui314** [comment]
Jumping into an inner scope is not allowed. See https://www.sigbus.info/n1570#6.8.6.1p1. It is up to a compiler to report it as an error or just do whatever it wants to do.

**Comment by ghost** [comment]
Aren’t statement expressions a GCC extension? (Rather than being standardized, I mean.) Because in that case, I think chibicc should try to match GCC’s behavior. If you don’t think it is worthwhile to fix this, I do, and I’d be willing to work on a patch for it if you are interested! (Likewise for #83.)

See:
- <https://gcc.gnu.org/onlinedocs/gcc/C-Extensions.html>
- <https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html>

From GCC’s docs:

> Jumping into a statement expression with goto or using a switch statement outside the statement expression with a case or default label inside the statement expression is not permitted. […]

Compare this wording with what it considers undefined behavior:

> […] Jumping into a statement expression with a computed goto […] has undefined behavior. […]

As a side note, I think the link you shared is not talking about statement expressions (since those are GCC extensions), but rather about jumping into the scope of a variable that is or includes a VLA (hence the wording “variably modified type”). Something like this:

~~~ C
int main(int argc, char **argv)
{
	goto foo;
	
	int vla[argc];
	
	foo:
	vla[0] = 0;
	
	return 0;
}
~~~

**Comment by ghost** [comment]
@rui314: I have created [a patch][diff.txt]! I’m really happy about it, as I think it is very succinct. Thoughts would be appreciated!

[diff.txt]: <https://github.com/rui314/chibicc/files/7934549/diff.txt>
