### ISSUE TITLE
Peephole optimizer

### ISSUE THREAD

**Issue by HPCguy** [rui314/chibicc#87]
I see you are generating code for a stack based machine.  The squint optimizer could be adapted to your project pretty easily.

https://github.com/HPCguy/Squint

**Comment by sgraham** [comment]
Squint looks interesting. It's ARM only though, right? chibicc is x64 only.

**Comment by HPCguy** [comment]
Yes, AARCH32.  Squint has undergone a lot of changes since I first posted this issue, and is much larger now.  All the optimizations should transfer over to x86, but at this point there is more work to do.  "Pretty easily" may no longer apply, but that said, I am not even an ARM programmer.  I wrote x86 assembly for decades and just started ARM a year or so ago.  You might want to retire this issue entirely, or I could look at bringing over some of the "low hanging fruit", high bang-for-the-buck optimizations to your compiler by submitting a pull request in your repo.  That said, I haven't been doing much work for the last two months due to a medical issue, so no promises on how soon I could summon the energy to port the best optimizations.

**Comment by HPCguy** [comment]
PS  The reason I referenced Squint here is because the stack virtual machine used by both compilers is essentially the same, so the transformations are very similar.

**Comment by sgraham** [comment]
Thank you for the information.

I'm actually playing around with making a JIT version of chibicc in a fork https://github.com/sgraham/dyibicc (similar to MC I guess?). I will take a look at Squint (maybe at an older/simpler revision) to see if I can reuse some of the code or ideas to add an optimization pass.

**Comment by HPCguy** [comment]
@sgraham I looked at your dynasm output.  It is definitely the same stack VM as Squint, but I recommend you modify the AST directly for dynasm optimization rather than going the Squint route of post processing.   Removing the nested push/pop pairs will greatly increase performance.  Good luck. 

I am closing this ticket in chibicc  since a Squint port is a heavy lift at this point, given that Squint is now much more complex.
